title: 'serxka.github.io'
description: "A jekyll blog hosted on github pages"
baseurl: "/"
url: "https://serxka.live"

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

footer: 'avoid social media, <a hfref="github.com/serxka">gh</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
